### ISSUE TITLE
Shared cloning

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#208]
Backstory: http://redmine.citytech.cuny.edu/issues/2313

We'd like to port the Shared Cloning feature from the OpenLab to CBOX-OL. The front-end functionality - what's shown to the group administrator as well as the group creator - should be a more-or-less straightforward port. But we may want to introduce a Dashboard interface for configuring, on a group-type level, (a) whether Shared Cloning is *enabled* for the group type, and (b) whether Shared Cloning is *on by default* for groups of a group type.

@jennaspevack Assigning to you for answers to this question, and a mockup of the necessary UI.

**Comment by boonebgorges** [comment]
@Mamaduka Could you please have a look at this issue in the upcoming days?

**Comment by boonebgorges** [comment]
I just added some Badge stuff this morning that will need attention as part of this feature - see the commented-out code here https://github.com/cuny-academic-commons/openlab-theme/blob/1.2.x/lib/group-funcs.php#L2980

**Comment by Mamaduka** [comment]
Hi @boonebgorges,

I noticed that `GroupType::get_can_be_cloned()` flag is used in few places. Based on OL implementation we're enabling this feature for every group type (except Portfolios). Do we still need to use this flag and provide new defaults for clonable group types?

I'll need to add/update group labels? Can you point me to the issue/commit, where I can see how this process is handled?

Thanks,

George

**Comment by boonebgorges** [comment]
>  Do we still need to use this flag

I'd say yes, leave it in place, but have it return `true` in all cases. This gives us the flexibility to change it later - or to add a filter for people to change the behavior themselves.

> provide new defaults for clonable group types

I don't understand this part of the question - could you clarify?

> I'll need to add/update group labels? Can you point me to the issue/commit, where I can see how this process is handled?

Ha, this system is kind of weird and I had to make my own notes for this too :) https://github.com/cuny-academic-commons/cbox-openlab-core/blob/aada7ba1425c0d6c07bbaa67f6f8487b3c0bd020/classes/GroupType.php#L298
1. Add entry in `GroupType::get_label_types()`
2. Add entry in `GroupType::get_label_types_info()` - this is where the name and description go
3. Add the slug to the list under the appropriate group types in `GroupType::get_labels()` https://github.com/cuny-academic-commons/cbox-openlab-core/blob/aada7ba1425c0d6c07bbaa67f6f8487b3c0bd020/classes/GroupType.php#L96
4. Add default values for each relevant group type https://github.com/cuny-academic-commons/cbox-openlab-core/blob/aada7ba1425c0d6c07bbaa67f6f8487b3c0bd020/classes/Install.php#L200
5. To restore defaults on your installation (installing the new strings), run `wp cboxol reset` and then `wp cboxol install`

**Comment by Mamaduka** [comment]
> >provide new defaults for clonable group types

>I don't understand this part of the question - could you clarify?

I mean installation defaults. Currently, only "Courses" can be cloned.

**Comment by boonebgorges** [comment]
Ah yes, I see. Yes, I think we should leave this default database flag. It doesn't really hurt anything, and it gives us flexibility down the road.

**Comment by Mamaduka** [comment]
Note: `wp cboxol install` fails to correctly generate labels with `cbox-openlab-core`, version 1.2.x.

Stack trace:
```
PHP Warning:  Illegal string offset 'value' in /plugins/cbox-openlab-core/classes/GroupType.php on line 264
....
CBOX\OL\GroupType->get_labels() /plugins/cbox-openlab-core/classes/ItemTypeBase.php:147
```

**Comment by boonebgorges** [comment]
Dangit, I just had to rewrite a bunch of stuff. Looking into it right now....

**Comment by boonebgorges** [comment]
@Mamaduka I think this should be fixed by a261089. I'll be able to take a closer look tomorrow if not :)

**Comment by boonebgorges** [comment]
(by https://github.com/cuny-academic-commons/cbox-openlab-core/commit/a26108989aa4b78695ce8b14ed28955a2d156a62 I mean)

**Comment by Mamaduka** [comment]
Thanks @boonebgorges.

I've only few minor issues left and will fix them first thing tomorrow morning. Then issue will be ready for testing.

**Comment by Mamaduka** [comment]
@boonebgorges,

The feature is ready, just a couple questions:
* Do we have an upgrade routine to add new labels in DB? Without `wp cboxol reset && wp cboxol install` plugin triggers PHP notices.
* OpenLab theme doesn't have cloned group history, but we have it on OL. Should I port this feature as well?

**Comment by boonebgorges** [comment]
> Do we have an upgrade routine to add new labels in DB? Without wp cboxol reset && wp cboxol install plugin triggers PHP notices.

No, we don't - thank you for the reminder. Please go ahead and set one up. I may need to add more to that list from other improvements this release - I'll check the diff once you've got the upgrade routine in place.

> OpenLab theme doesn't have cloned group history, but we have it on OL. Should I port this feature as well?

Yes, I think it's an important part of Shared Cloning, since if you clone someone else's work, you should be crediting them for it.

**Comment by Mamaduka** [comment]
This feature is ready for testing.

Requires: https://github.com/cuny-academic-commons/cbox-openlab-core/pull/13.

**Comment by boonebgorges** [comment]
Thanks, @Mamaduka - I've merged that PR and run the upgrade routine on openlabdev.commonsinabox.org so that the team can test the feature.

**Comment by bree-z** [comment]
Shared cloning looks mostly good, thanks! 

There are a few tickets for cloning more generally that also affect shared cloning, but otherwise the process is working correctly.  

There are only two things I noticed that differ from the OpenLab. I'm not sure if these are bugs, or just not compatible with CBOX OL:

1. The Sharing widget doesn't appear when shared cloning is activated for a group. And the Sharing widget and the Credits widget do not appear on sites cloned through shared cloning. 
2. The text that appears on the OpenLab profile and site widgets for non-authenticated users doesn't appear on CBOX OL: "This course may be cloned by logged-in faculty." or "This project may be cloned by logged-in OpenLab members." (or same for clubs). I realize that this may be a translation issue, but just wanted to raise the question.

Thanks!

<img width="891" alt="Screen Shot 2020-08-06 at 2 57 48 PM" src="https://user-images.githubusercontent.com/7189824/89571455-b1e8ba00-d7f5-11ea-91ea-cd5af3fe022b.png">

**Comment by boonebgorges** [comment]
Thanks, Bree. It looks like the widgets and the '...may be cloned by... ' text were left out when @Mamaduka ported this feature over.

I've done this work and it's now ready to test on openlabdev.commonsinabox.org. In a few ways, it differs from what's on the OpenLab:

- The text you describe in your (2) has been simplified. I've shortened it to 'May be cloned by logged-in users.' There is no differentiation of courses and non-courses, because it's not possible to translate these strings - the term "faculty" as well as the term "course" are user-configurable in a way that can't easily be reconciled. In addition, it makes life much simpler to remove the 'This course'/'This project'/etc prefix.

- Similarly, the text of the Sharing widget is simplified somewhat. I've removed the distinction between courses and non-courses. Logged-in users always see 'Clone this [group type]', and logged-out users see 'Logged-in members can clone.'

**Comment by bree-z** [comment]
Thanks, Boone. A few questions/issues:

1. Would it work change the text from 'May be cloned by logged-in users.' to: 'May be cloned by logged-in community members.'?

This would make it more in line with similar text such as: 'This Course is OPEN, but only logged-in community members may view the corresponding Site.'

2. The widgets are still not being added to the site.

When I enabled shared cloning for this course, the Sharing widget was not added to the associated site:

https://openlabdev.commonsinabox.org/groups/ways-of-seeing-fylc-fall-2019/

And, when I cloned ways-of-seeing-fylc-fall-2019/ the Credits widget was not added to the cloned site:

Source: https://openlabdev.commonsinabox.org/groups/ways-of-seeing-shared-clone/
Clone: https://openlabdev.commonsinabox.org/groups/ways-of-seeing-fylc-fall-2019/ 

3. And sorry, I missed something last time since I've gotten used to seeing the credits on the Group Home for projects and clubs as 'Project - Author Name' or 'Club - Author Name'.  On the OpenLab, however, for courses we pull the Course Code and only use 'Course - Prof. Name' if there's no data in the source Course Code field. Is that possible to do here? And if not for this release, for a future release?

Thanks!

**Comment by bree-z** [comment]
Sorry, closed by accident!

**Comment by boonebgorges** [comment]
> Would it work change the text from 'May be cloned by logged-in users.' to: 'May be cloned by logged-in community members.'?

>  On the OpenLab, however, for courses we pull the Course Code and only use 'Course - Prof. Name' if there's no data in the source Course Code field. Is that possible to do here? 

I've made these changes.

>  The widgets are still not being added to the site.

Here we are descending into the darkest hell of WP internals. A few days ago there was an issue where the clone widgets were causing groupless sites (like the main site) to crash in the Customizer. My fix there apparently won't work across the board because of the order in which WP registers its widgets and loads its other libraries. The result was that the widgets weren't registered in time to be added when you were creating the course. I've rearranged the way that all of this works. The upshot is that you will now see the Sharing and Credits widgets on groupless sites (like the main site) and they will no longer crash the Customizer, but they obviously will have nothing to display in those cases.

**Comment by bree-z** [comment]
Sorry to send you to the darkest hell of WP internals! But, it seems to have done the trick. 

The Sharing widget is now activated whenever shared cloning is enabled. And the Credits widget is also added to sites created via shared cloning.

Thanks!
