### ISSUE TITLE
Main menu not usable at medium-width screen sizes

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#321]
Hi Boone, 

As [reported](https://commonsinabox.org/groups/openlab-help-support/forum/topic/help-does-not-show-in-top-menu-when-logged-out-of-the-ol/) in the support forum, the main menu (About, Members, Courses, Projects, etc) disappears behind the toolbar and is no longer usable. Then at narrow widths it switches to the hamburger menu. More from the forum post, which I was able to reproduce:

> The top menu does not always have graceful fallback for mobile responsive.
> 
> - On oneonta.sunycreate.cloud at Laptop Width (1024 px) the top menu is present at usable.
> - When we drop down to iPad Width (768 px) the top menu disappears and is not usable.
> - However, it isn’t until (425 px) that the drop-down alternative to the top menu appears.
> 
> So it appears that there is a gap in the CSS for medium size screens where the top menu isn’t usable but the mobile replacement hasn’t been included. The bottom menu operates on slightly different rules, where the bottom menu will still appear on iPad sized screens, but it will sometimes take up two lines instead of 1.

There was also a [second issue](https://commonsinabox.org/groups/openlab-help-support/forum/topic/emails-and-invitations/) with responsiveness reported, which I cannot reproduce, but I'm including it here in case it's related. The user reports that on an iPhone 10, the 'My Invitations' submenu disappears. See his screenshots here: https://commonsinabox.org/groups/openlab-help-support/forum/topic/emails-and-invitations/ 

I've tried to reproduce on an iPhone 7 and iPad, plus also using an emulator for numerous mobile devices and narrowing my browser window to various sizes. I've also tried on Chrome, Firefox, and Safari.

Thanks!

**Main menu at medium width:**

<img width="804" alt="CBOXOL_MediumWidth" src="https://user-images.githubusercontent.com/7189824/101883882-dd91fd00-3b65-11eb-94a7-076a4117acbd.png">

**Main menu at narrow width:**

<img width="438" alt="CBOXOL_NarrowWidth" src="https://user-images.githubusercontent.com/7189824/101883899-e682ce80-3b65-11eb-88ca-a84432fbf20b.png">

**Comment by boonebgorges** [comment]
> So it appears that there is a gap in the CSS for medium size screens where the top menu isn’t usable but the mobile replacement hasn’t been included. 

The problem here is this:
1. The hamburger toolbar is enabled when screen width is 767px or less
2. The main nav appears to the right of the logo. When the main nav gets too wide for the available space on that line, it drops down to the next line
3. The default menu configuration for CBOX-OL - the default menu items, with the default labels (in English, using default words like 'Clubs' and 'Projects'), when the user is logged in so that 'My Profile' is appended, is just a bit wider than the available space. So it breaks to the second line around 812px.
4. The non-hamburger toolbar's position from the top of the screen is fixed, so it doesn't bump down when the main nav jumps to the second line.

There is no straightforward solution, in part because everything runs through separate systems. 1 is a WordPress core feature, triggered by CSS rules that are not straightforward to override. 4 is partly a WordPress issue but CBOX-OL gets involved somewhat because of the custom height of the CBOX-OL toolbar. 

Here are some possible paths forward:

a. Modify the main nav styling so that the main nav, at least with the default items, is small enough to prevent this from happening. We would need to trim about 50px. We could do this by squeezing the padding/margins a bit, or whatever. This is a bit finicky, and it won't account for other configs (more menu items, longer menu items) but at least it would cover the default config. The main advantage here is that it's fairly easy to accomplish technically.
b. Change the default nav items so that there are fewer of them. Eg: remove Help, or About, or Calendar, or perhaps hide those items at medium widths.
c. We do have a medium breakpoint (Bootstrap's "medium", 992px) where we bump down the logo size and the nav font size. We could try to bump this down even further. Maybe not ideal for accessibility or visuals, but it might be good enough to get by.
d. Try to change the breakpoints so that we switch to the hamburger earlier. Given the fact that we inherit this code from WP, it's very difficult to make this happen, so I don't recommend pursuing it.
e. Try to change the positioning of the toolbar so that it bumps down if the main nav spills to a second line. At least this would allow it to be visible, even if it's not ideal visually. This is also likely to be quite hard, and is not ideal from a functional point of view, so I don't recommend it.

Some of these are doable in the short term, while others require a large rewrite of what is already a complicated and somewhat broken system. See eg #315.

**Comment by boonebgorges** [comment]
In the absence of better ideas, I went with a version of (c). Screenshot:
![Screenshot_2021-01-08_18-06-11](https://user-images.githubusercontent.com/246627/104049502-f7fadd00-51dc-11eb-97c3-0ea8493a2f16.png)

Not great, but usable. Let's see how this works for the upcoming release.

**Comment by bree-z** [comment]
Thanks, Boone! I still see the same thing (after clearing my cache just in case). 

**My Profile**

<img width="1089" alt="Screen Shot 2021-01-12 at 3 12 30 PM" src="https://user-images.githubusercontent.com/7189824/104367425-ca69a880-54e8-11eb-8ee1-e76dcf6f7f18.png">

**Homepage**

<img width="1090" alt="Screen Shot 2021-01-12 at 3 12 11 PM" src="https://user-images.githubusercontent.com/7189824/104367444-d190b680-54e8-11eb-9e66-863e019ee20c.png">

**Comment by boonebgorges** [comment]
It's working, but it's not 100% perfect because the test site uses longer labels - specifically 'Community Projects' - than the default configuration. Your screenshots must be from bad widths. Some screenshots (note the widths):

1010px - works
![Screenshot_2021-01-12_15-10-43](https://user-images.githubusercontent.com/246627/104375060-647d2100-54e8-11eb-8078-d7472b4f5486.png)

1000px - doesn't work, because responsive breakpoint hasn't yet kicked in (991px) but the nav item length is still wide enough to kick down to the second row
![Screenshot_2021-01-12_15-11-21](https://user-images.githubusercontent.com/246627/104375154-88406700-54e8-11eb-8bbe-9b914cdd73e1.png)

990px - works, just past the breakpoint
![Screenshot_2021-01-12_15-12-24](https://user-images.githubusercontent.com/246627/104375209-9b533700-54e8-11eb-9be0-21c1e7d2e257.png)

800px - Still works, this is about as narrow as you can get with this set of nav item labels
![Screenshot_2021-01-12_15-13-34](https://user-images.githubusercontent.com/246627/104375315-c76eb800-54e8-11eb-9e40-38e6b6bb089f.png)

770px - Broken, similar to 1000px case
![Screenshot_2021-01-12_15-15-33](https://user-images.githubusercontent.com/246627/104375504-16b4e880-54e9-11eb-98d9-2021a3109981.png)

765px - Just past the mobile breakpoint, works
![Screenshot_2021-01-12_15-16-32](https://user-images.githubusercontent.com/246627/104375554-2af8e580-54e9-11eb-92d4-afcee57bbc38.png)

It may be able to tweak slightly, but there will always be limits if you enter long nav item titles. This is unavoidable without a larger rewrite.

**Comment by bree-z** [comment]
Aha, I see. If I edit the long menu names, I don't have a problem at medium widths. Thanks Boone! 

I think this is OK to close.
